name: bootstrap
description: Bootstrap's files, in a pub package. Contains
             Bootstrap 4.0.0-alpha.6
             Included is a transformer to swap the CSS for a CDN version.
authors:
- Bootstrap core team
- Victor Berchet <victor@suumit.com>
- Seth Ladd <sethladd@gmail.com>
- Richer Larivière <richerlariviere@gmail.com>
version: 4.0.0-alpha.6
homepage: https://github.com/richerlariviere/bootstrap_for_pub
dependencies:
  barback: ">=0.14.1+3 <0.16.0"
  html: ">=0.12.2+2 <0.13.2"
